### ISSUE TITLE
Next paper candidates: 14 Sep

### ISSUE THREAD

**Issue by bzz** [src-d/reading-club#1]
Starting a thread with suggestions on the papers for the next session on _Sep 14th_

**Comment by m09** [comment]
- [Mapping Language to Code in Programmatic Context](https://arxiv.org/pdf/1808.09588.pdf)
- [A Tree-based Decoder for Neural Machine Translation](https://arxiv.org/pdf/1808.09374.pdf)

**Comment by zurk** [comment]
I like to discuss everything related to tree analysis. We have a bunch in our repo https://github.com/src-d/awesome-machine-learning-on-source-code like this one https://arxiv.org/pdf/1802.00921.pdf

and @m09's suggestion is also good.

**Comment by bzz** [comment]
Miltos Allamanis, Marc Brockschmidt, and Mahmoud Khademi  ["Learning to Represent Programs with Graphs](https://arxiv.org/abs/1711.00740)" , 2017

**Comment by xennygrimmato** [comment]
[Code Vectors: Understanding Programs Through Embedded Abstracted Symbolic Traces](https://arxiv.org/abs/1803.06686)
