### ISSUE TITLE
2018.12.14 paper has the wrong link

### ISSUE THREAD

**Issue by BCasaleiro** [src-d/reading-club#29]
In [Past Papers](https://github.com/src-d/reading-club#past-papers), the link of the **2018.12.14** paper, "Improving Automatic Source Code Summarization via Deep Reinforcement Learning", is pointing to the **2019.01.11** paper, "A general reinforcement learning algorithm that masters chess, shogi and Go through self-play".

**Comment by m09** [comment]
Fixed via #30. Thanks @BCasaleiro!
