### ISSUE TITLE
Next paper candidates: 28 Sep

### ISSUE THREAD

**Issue by m09** [src-d/reading-club#3]
# Next paper candidates
Let's propose papers to study next! All papers mentioned in the comments of this issue as well as runner-up(s) from the last session will be listed in the next vote.

**Comment by bzz** [comment]
“A Tree-based Decoder for Neural Machine Translation” looks interesting.

**Comment by EgorBu** [comment]
[`code2seq: Generating Sequences from Structured Representations of Code`](https://arxiv.org/pdf/1808.01400v1.pdf):
```
The ability to generate natural language sequences from source code snippets can be
used for code summarization, documentation, and retrieval. Sequence-to-sequence
(seq2seq) models, adopted from neural machine translation (NMT), have achieved
state-of-the-art performance on these tasks by treating source code as a sequence of
tokens. We present CODE2SEQ: an alternative approach that leverages the syntactic
structure of programming languages to better encode source code. Our model
represents a code snippet as the set of paths in its abstract syntax tree (AST) and
uses attention to select the relevant paths during decoding, much like contemporary
NMT models. We demonstrate the effectiveness of our approach for two tasks,
two programming languages, and four datasets of up to 16M examples. Our
model significantly outperforms previous models that were specifically designed
for programming languages, as well as general state-of-the-art NMT models.
```

**Comment by Jan21** [comment]
More SQL stuff:
[Robust Text-to-SQL Generation with Execution-Guided Decoding
](https://arxiv.org/abs/1807.03100)
We consider the problem of neural semantic parsing, which translates natural language questions into executable SQL queries. We introduce a new mechanism, execution guidance, to leverage the semantics of SQL. It detects and excludes faulty programs during the decoding procedure by conditioning on the execution of partially generated program. The mechanism can be used with any autoregressive generative model, which we demonstrate on four state-of-the-art recurrent or template-based semantic parsing models. We demonstrate that execution guidance universally improves model performance on various text-to-SQL datasets with different scales and query complexity: WikiSQL, ATIS, and GeoQuery. As a result, we achieve new state-of-the-art execution accuracy of 83.8% on WikiSQL.

[IncSQL: Training Incremental Text-to-SQL Parsers with Non-Deterministic Oracles
](https://arxiv.org/abs/1809.05054v1)
We present a sequence-to-action parsing approach for the natural language to SQL task that incrementally fills the slots of a SQL query with feasible actions from a pre-defined inventory. To account for the fact that typically there are multiple correct SQL queries with the same or very similar semantics, we draw inspiration from syntactic parsing techniques and propose to train our sequence-to-action models with non-deterministic oracles. We evaluate our models on the WikiSQL dataset and achieve an execution accuracy of 83.7% on the test set, a 2.1% absolute improvement over the model trained with traditional static oracles assuming a single correct target SQL query. When further combined with the execution-guided decoding strategy, our model sets a new state-of-the-art performance at an execution accuracy of 87.1%. 

[Natural Language to Structured Query Generation via Meta-Learning](https://arxiv.org/abs/1803.02400)

n conventional supervised training, a model is trained to fit all the training examples. However, having a monolithic model may not always be the best strategy, as examples could vary widely. In this work, we explore a different learning protocol that treats each example as a unique pseudo-task, by reducing the original learning problem to a few-shot meta-learning scenario with the help of a domain-dependent relevance function. When evaluated on the WikiSQL dataset, our approach leads to faster convergence and achieves 1.1%-5.4% absolute accuracy gains over the non-meta-learning counterparts.

**Comment by m09** [comment]
Among last week runner-ups: [Code Vectors: Understanding Programs Through Embedded Abstracted Symbolic Traces](https://arxiv.org/abs/1803.06686)

> With the rise of machine learning, there is a great deal of interest in treating programs as data to be fed to learning algorithms. However, programs do not start off in a form that is immediately amenable to most off-the-shelf learning techniques. Instead, it is necessary to transform the program to a suitable representation before a learning technique can be applied. 
> In this paper, we use abstractions of traces obtained from symbolic execution of a program as a representation for learning word embeddings. We trained a variety of word embeddings under hundreds of parameterizations, and evaluated each learned embedding on a suite of different tasks. In our evaluation, we obtain 93% top-1 accuracy on a benchmark consisting of over 19,000 API-usage analogies extracted from the Linux kernel. In addition, we show that embeddings learned from (mainly) semantic abstractions provide nearly triple the accuracy of those learned from (mainly) syntactic abstractions.

**Comment by m09** [comment]
Among last week runner-ups: [A Tree-based Decoder for Neural Machine Translation](https://arxiv.org/pdf/1808.09374.pdf)
> Recent advances in Neural Machine Translation (NMT) show that adding syntactic information to NMT systems can improve the quality of their translations. Most existing work utilizes some specific types of linguistically-inspired tree structures, like constituency and dependency parse trees. This is often done via a standard RNN decoder that operates on a linearized target tree structure. However, it is an open question of what specific linguistic formalism, if any, is the best structural representation for NMT. In this paper, we (1) propose an NMT model that can naturally generate the topology of an arbitrary tree structure on the target side, and (2) experiment with various target tree structures. Our experiments show the surprising result that our model delivers the best improvements with balanced binary trees constructed without any linguistic knowledge; this model outperforms standard seq2seq models by up to 2.1 BLEU points, and other methods for incorporating target-side syntax by up to 0.7 BLEU.

**Comment by EgorBu** [comment]
[SQL-to-Text Generation with Graph-to-Sequence Model](https://arxiv.org/abs/1809.05255v1)
>Previous work approaches the SQL-to-text generation task using vanilla Seq2Seq models, which may not fully capture the inherent graph-structured information in SQL query. In this paper, we first introduce a strategy to represent the SQL query as a directed graph and then employ a graph-to-sequence model to encode the global structure information into node embeddings. This model can effectively learn the correlation between the SQL query pattern and its interpretation. Experimental results on the WikiSQL dataset and Stackoverflow dataset show that our model significantly outperforms the Seq2Seq and Tree2Seq baselines, achieving the state-of-the-art performance.

**Comment by m09** [comment]
[StructVAE: Tree-structured Latent Variable Models for Semi-supervised Semantic Parsing](http://aclweb.org/anthology/P18-1070)
> Semantic parsing is the task of transducing natural language (NL) utterances into formal meaning representations (MRs), commonly represented as tree structures. Annotating NL utterances with their corresponding MRs is expensive and time-consuming, and thus the limited availability of labeled data often becomes the bottleneck of data-driven, supervised models. We introduce StructVAE, a variational auto-encoding model for semi-supervised semantic parsing, which learns both from limited amounts of parallel data, and readily-available unlabeled NL utterances. StructVAE models latent MRs not observed in the unlabeled data as tree-structured latent variables. Experiments on semantic parsing on the ATIS domain and Python code generation show that with extra unlabeled data, StructVAE outperforms strong supervised models.

**Comment by bzz** [comment]
And the winner is `code2seq: Generating Sequences from Structured Representations of Code: https://arxiv.org/pdf/1808.01400.pdf` -  `5`
