### ISSUE TITLE
Next paper candidates: 8 Feb

### ISSUE THREAD

**Issue by m09** [src-d/reading-club#31]
# Next paper candidates
Let's propose papers to study next! All papers mentioned in the comments of this issue will be listed in the next vote.

**Comment by m09** [comment]
Last session runner-up: [Structured Neural Summarization](https://openreview.net/forum?id=H1ersoRqtm)

> Summarization of long sequences into a concise statement is a core problem in natural language processing, requiring non-trivial understanding of the input. Based on the promising results of graph neural networks on highly structured data, we develop a framework to extend existing sequence encoders with a graph component that can reason about long-distance relationships in weakly structured data such as text. In an extensive evaluation, we show that the resulting hybrid sequence-graph models outperform both pure sequence models as well as pure graph models on a range of summarization tasks.

**Comment by bzz** [comment]
["The Adverse Effects of Code Duplication in Machine Learning Models of Code"](https://arxiv.org/abs/1812.06469), 2018

> The field of big code relies on mining large corpora of code to perform some learning task. A significant threat to this approach has been recently identified by Lopes et al. (2017) who found a large amount of code duplication on GitHub. However, the impact of code duplication has not been noticed by researchers devising machine learning models for source code. In this article, we study the effect of code duplication to machine learning models showing that reported metrics are sometimes inflated by up to 100% when testing on duplicated code corpora compared to the performance on de-duplicated corpora which more accurately represent how machine learning models of code are used by software engineers. We present an "errata" for widely used datasets, list best practices for collecting code corpora and evaluating machine learning models on them, and release tools to help the community avoid this problem in future research.

**Comment by bzz** [comment]
The poll is on https://sourced-community.slack.com/archives/CCLPL1WQH/p1549276013015000

**Comment by bzz** [comment]
`Structured Neural Summarization`  https://arxiv.org/abs/1811.01824 has been chosen :tada:
