### ISSUE TITLE
Next paper candidates: 5 April

### ISSUE THREAD

**Issue by m09** [src-d/reading-club#44]
# Next paper candidates
Let's propose papers to study next! All papers mentioned in the comments of this issue will be listed in the next vote.

## Last session runner-up(s)
 - [How Powerful are Graph Neural Networks? ](https://arxiv.org/abs/1810.00826)
  
   > Graph Neural Networks (GNNs) are an effective framework for representation learning of graphs. GNNs follow a neighborhood aggregation scheme, where the representation vector of a node is computed by recursively aggregating and transforming representation vectors of its neighboring nodes. Many GNN variants have been proposed and have achieved state-of-the-art results on both node and graph classification tasks. However, despite GNNs revolutionizing graph representation learning, there is limited understanding of their representational properties and limitations. Here, we present a theoretical framework for analyzing the expressive power of GNNs to capture different graph structures. Our results characterize the discriminative power of popular GNN variants, such as Graph Convolutional Networks and GraphSAGE, and show that they cannot learn to distinguish certain simple graph structures. We then develop a simple architecture that is provably the most expressive among the class of GNNs and is as powerful as the Weisfeiler-Lehman graph isomorphism test. We empirically validate our theoretical findings on a number of graph classification benchmarks, and demonstrate that our model achieves state-of-the-art performance.

   A theory behind GNNs

 - [GRAPH ATTENTION NETWORKS](https://arxiv.org/pdf/1710.10903.pdf)

   > We present graph attention networks (GATs), novel neural network architectures that operate on graph-structured data, leveraging masked self-attentional layers to address the shortcomings of prior methods based on graph convolutions or their approximations. By stacking layers in which nodes are able to attend over their neighborhoods’ features, we enable (implicitly) specifying different weights to different nodes in a neighborhood, without requiring any kind of costly matrix operation (such as inversion) or depending on knowing the graph structure upfront. In this way, we address several key challenges of spectral-based graph neural networks simultaneously, and make our model readily applicable to inductive as well as transductive problems. Our GAT models have achieved or matched state-of-theart results across four established transductive and inductive graph benchmarks: the Cora, Citeseer and Pubmed citation network datasets, as well as a proteinprotein interaction dataset (wherein test graphs remain unseen during training).

   With accompanying blog post and implementation: https://www.dgl.ai/blog/2019/02/17/gat.html

**Comment by bzz** [comment]
The poll is on! https://sourced-community.slack.com/archives/CCLPL1WQH/p1554133959000800

**Comment by m09** [comment]
And the winner is: [How Powerful are Graph Neural Networks?](https://arxiv.org/abs/1810.00826)
 (https://sourced-community.slack.com/archives/CCLPL1WQH/p1554190057001100) :tada:
