### ISSUE TITLE
Next paper candidates: 19 April

### ISSUE THREAD

**Issue by bzz** [src-d/reading-club#48]
# Next paper candidates
Let's propose papers to study next! All papers mentioned in the comments of this issue will be listed in the next vote.

## Last session runner-up

[Graph Attention Networks](https://arxiv.org/pdf/1710.10903.pdf) by Petar Veličković, Guillem Cucurull, Arantxa Casanova, Adriana Romero, Pietro Liò and Yoshua Bengio.

> We present graph attention networks (GATs), novel neural network architectures that operate on graph-structured data, leveraging masked self-attentional layers to address the shortcomings of prior methods based on graph convolutions or their approximations. By stacking layers in which nodes are able to attend over their neighborhoods' features, we enable (implicitly) specifying different weights to different nodes in a neighborhood, without requiring any kind of costly matrix operation (such as inversion) or depending on knowing the graph structure upfront. In this way, we address several key challenges of spectral-based graph neural networks simultaneously, and make our model readily applicable to inductive as well as transductive problems. Our GAT models have achieved or matched state-of-the-art results across four established transductive and inductive graph benchmarks: the Cora, Citeseer and Pubmed citation network datasets, as well as a protein-protein interaction dataset (wherein test graphs remain unseen during training).

**Comment by bzz** [comment]
["Maybe Deep Neural Networks are the Best Choice for Modeling Source Code"](https://arxiv.org/abs/1903.05734) by Rafael-Michael Karampatsis and Charles Sutton
 
> Statistical language modeling techniques have successfully been applied to source code, yielding a variety of new software development tools, such as tools for code suggestion and improving readability. A major issue with these techniques is that code introduces new vocabulary at a far higher rate than natural language, as new identifier names proliferate. But traditional language models limit the vocabulary to a fixed set of common words. For code, this strong assumption has been shown to have a significant negative effect on predictive performance. But the open vocabulary version of the neural network language models for code have not been introduced in the literature. We present a new open-vocabulary neural language model for code that is not limited to a fixed vocabulary of identifier names. We employ a segmentation into subword units, subsequences of tokens chosen based on a compression criterion, following previous work in machine translation. Our network achieves best in class performance, outperforming even the state-of-the-art methods of Hellendoorn and Devanbu that are designed specifically to model code. Furthermore, we present a simple method for dynamically adapting the model to a new test project, resulting in increased performance. We showcase our methodology on code corpora in three different languages of over a billion tokens each, hundreds of times larger than in previous work. To our knowledge, this is the largest neural language model for code that has been reported.

HT @Jan21 for sharing it!

**Comment by bzz** [comment]
[Bilateral Dependency Neural Networks for Cross-Language Algorithm Classification](https://bdqnghi.github.io/files/SANER_2019_bilateral_dependency.pdf)

> Algorithm classification is to automatically identify
> the classes of a program based on the algorithm(s) and/or data
> structure(s) implemented in the program. It can be useful for
> various tasks, such as code reuse, code theft detection, and malware
> detection. Code similarity metrics, on the basis of features
> extracted from syntax and semantics, have been used to classify
> programs. Such features, however, often need manual selection
> effort and are specific to individual programming languages,
> limiting the classifiers to programs in the same language.
> We have instantiated the framework with several kinds of
> token-, tree- and graph-based neural networks that encode and
> learn various kinds of information in code. We have applied
> the instances of the framework to a code corpus collected from
> GitHub containing thousands of Java and C++ programs implementing
> 50 different algorithms and data structures. Our evaluation
> results show that the use of Bi-NN indeed produces promising
> algorithm classification results both within one language and
> across languages, and the encoding of dependencies from code
> into the underlying neural networks helps improve algorithm
> classification accuracy further. In particular, our custom-built
> dependency trees with tree-based convolutional neural networks
> achieve the highest classification accuracy among the different
> instances of the framework that we have evaluated. Our study
> points to a possible future research direction to tailor bilateral
> and multilateral neural networks that encode more relevant
> semantics for code learning, mining and analysis tasks

**Comment by m09** [comment]
[A Comprehensive Survey on Graph Neural Networks](https://arxiv.org/pdf/1901.00596.pdf)

> Deep learning has revolutionized many machine learning tasks in recent years, ranging from image classification and video processing to speech recognition and natural language understanding. The data in these tasks are typically represented in the Euclidean space. However, there is an increasing number of applications where data are generated from non-Euclidean domains and are represented as graphs with complex relationships and interdependency between objects. The complexity of graph data has imposed significant challenges on existing machine learning algorithms. Recently, many studies on extending deep learning approaches for graph data have emerged. In this survey, we provide a comprehensive overview of graph neural networks (GNNs) in data mining and machine learning fields. We propose a new taxonomy to divide the state-of-the-art graph neural networks into different categories. With a focus on graph convolutional networks, we review alternative architectures that have recently been developed; these learning paradigms include graph attention networks, graph autoencoders, graph generative networks, and graph spatial-temporal networks. We further discuss the applications of graph neural networks across various domains and summarize the open source codes and benchmarks of the existing algorithms on different learning tasks. Finally, we propose potential research directions in this fast-growing field.

**Comment by m09** [comment]
Poll is on at https://sourced-community.slack.com/archives/CCLPL1WQH/p1555077201001000

**Comment by m09** [comment]
Poll is over! We will study A Comprehensive Survey on Graph Neural Networks :tada:
