### ISSUE TITLE
Online sessions

### ISSUE THREAD

**Issue by fyzbt** [src-d/reading-club#57]
Have you closed the option of participating in a discussion online? The README says meetings are held both online and offline, it's 16.30 CET and the zoom meeting hasn't started yet ( :( ) so that why I'm wondering

**Comment by m09** [comment]
Hi @fyzbt! Sorry for the bad experience. We still have online sessions, but due to a lack of foresight on my part, we did not use the usual zoom ID last time (I was on vacation and didn't plan for a way to hold the meeting at the usual ID).

We'll fix that for the next times it might happen.
