### ISSUE TITLE
Increase the bus factor for the meeting creation

### ISSUE THREAD

**Issue by m09** [src-d/reading-club#58]
When I'm on leave, we currently cannot hold the meeting at the usual ID. It should be fixed.

**Comment by bzz** [comment]
Ideally, it should be configured to start by itself with the fixed ID based on schedule.

May be @vcoisne or @marnovo could give us a hand here and teach how to do that with Zoom?

**Comment by vcoisne** [comment]
@m09 You should be able to edit the meeting to allow "Join before host"
<img width="767" alt="Screen Shot 2019-05-21 at 12 01 28 PM" src="https://user-images.githubusercontent.com/5384543/58124349-e0fc1700-7bc2-11e9-8236-2e4fea5dd244.png">

**Comment by m09** [comment]
Indeed, thanks @vcoisne for the tip :)

**Comment by m09** [comment]
Confirmed working :pray:
